<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Hyakkei.App</RootNamespace>
    <AssemblyName>HyakkeiTools</AssemblyName>
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.5.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.ico" />
    <Resource Include="Assets\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hyakkei.Core\Hyakkei.Core.csproj" />
    <ProjectReference Include="..\Tools\Hyakkei.Tool.AutoClicker\Hyakkei.Tool.AutoClicker.csproj" />
    <ProjectReference Include="..\Tools\Hyakkei.Tool.Translator\Hyakkei.Tool.Translator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.4.1" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

</Project>
